site_name: pyZ3

repo_name: yourusername/pyZ3
repo_url: https://github.com/amiyamandal-dev/pyz3

theme:
  name: material
  palette:
    primary: custom
    accent: custom
  features:
    - navigation.indexes
    #- navigation.tabs
    - navigation.expand
    - content.code.annotate

nav:
  - "index.md"
  - 'Getting Started': "getting_started.md"
  - 'User Guide':
    - "guide/index.md"
    - 'Modules': "guide/modules.md"
    - 'Functions': "guide/functions.md"
    - 'Classes': "guide/classes.md"
    - 'Exceptions': "guide/exceptions.md"
    - 'GIL': "guide/gil.md"
    - 'Testing': "guide/_4_testing.md"
    - 'Memory Management': "guide/_5_memory.md"
    - 'Buffer Protocol': "guide/_6_buffers.md"
    - 'NumPy Integration': "guide/numpy.md"

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/amiyamandal-dev/pyz3
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/pyZ3/
  version:
    provider: mike

extra_css:
  - stylesheets/extra.css

plugins:
- include-markdown
- mike

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      linenums: true
      anchor_linenums: true
      line_spans: __span
      use_pygments: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      dedent_subsections: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - tables
